### ISSUE TITLE
Possible memory Leak in AIOKafkaConsumer

### ISSUE THREAD

**Issue by diogovieira** [aio-libs/aiokafka#487]
Possibly related to #444 and #436.

I'm reproducing a memory leak with the following (relevant) code:

```python
def _deserializer(serialized):
    return json.loads(serialized)


class Consumer(ConsumerRebalanceListener):

    def __init__(self):
        self.message_buffer = []
        self.message_flush_last_t = time()
        self.message_buffer_lock = asyncio.Lock()
        self.flush_count = 10000
        self.flush_interval = 5
        self.origin = get_origin()
        self.consumer = AIOKafkaConsumer(loop=asyncio.get_event_loop(),
                                          bootstrap_servers=URL,
                                          value_deserializer=_deserializer,
                                          client_id=f'test-sw-leak-{self.origin}',
                                          group_id=f'test-sw-leak-{self.origin}',
                                          request_timeout_ms=30000,
                                          session_timeout_ms=10000,
                                          metadata_max_age_ms=10000,
                                          connections_max_idle_ms=600000,
                                          enable_auto_commit=True,
                                          auto_offset_reset='latest')

    async def consume(self):
        await self.consumer.start()
        self.consumer.subscribe(topics=['topic'])

        while True:
            try:
                message = await self.consumer.getone()
            except Exception as e:
                print(e)
                continue

            with await self.message_buffer_lock:
                if message:
                    self.message_buffer.append(message)

                buffer_count = len(self.message_buffer)
                if buffer_count > 0 and (buffer_count >= self.flush_count or
                                         (time() - self.message_flush_last_t) >= self.flush_interval):
                    try:
                        await self.consumer.commit()
                        self.message_flush_last_t = time()
                        self.message_buffer.clear()
                    except:
                        pass

if __name__ == '__main__':
    loop = asyncio.get_event_loop()

    loop.run_until_complete(Consumer().consume())

    try:
        loop.run_forever()
    finally:
        loop.close()
```

This test case doesn't generate lots of leaks but the memory is constantly increasing. Since I'm using multiple threads each with its consumer in my process I end up having to restart my server every hour.

One possibly relevant thing is, after running tracemalloc in my server I found similar resuls to those in #436.

Reproducible with Python 3.6.7 and aiokafka 0.5.0.

**Comment by tvoinarovskyi** [comment]
Thanks, a lot of those callbacks were removed in master. If you could try the master branch to see if memory is increasing would be grateful.
Will try to tackle it as soon as I get a chance. Maybe tomorrow.

**Comment by tvoinarovskyi** [comment]
Also trying Python3.7 may mitigate the issue if the callback leak with shield was fixed in asyncio. Still need a workaround for that.

**Comment by tvoinarovskyi** [comment]
@diogovieira After several tests I failed to reproduce a memory leak in the use case above. I tried to follow the example as close as possible. Here is the exact script I used to test memory consumption:

```Python
import asyncio
import json
from time import time
from aiokafka import AIOKafkaConsumer

import tracemalloc
import gc
from pprint import pprint

tracemalloc.start()


def _deserializer(serialized):
    return json.loads(serialized)


class Consumer:

    def __init__(self):
        self.message_buffer = []
        self.message_flush_last_t = time()
        self.message_buffer_lock = asyncio.Lock()
        self.flush_count = 10000
        self.flush_interval = 5
        self.consumer = AIOKafkaConsumer(
            loop=asyncio.get_event_loop(),
            bootstrap_servers="localhost:9092",
            value_deserializer=_deserializer,
            client_id='test-sw-leak',
            group_id='test-sw-leak',
            request_timeout_ms=30000,
            session_timeout_ms=10000,
            metadata_max_age_ms=10000,
            connections_max_idle_ms=600000,
            enable_auto_commit=True,
            auto_offset_reset='latest')

    async def consume(self):
        await self.consumer.start()
        self.consumer.subscribe(topics=['topic'])

        while True:
            message = await self.consumer.getone()

            with await self.message_buffer_lock:
                self.message_buffer.append(message)

                buffer_count = len(self.message_buffer)
                if buffer_count > 0 and (
                        buffer_count >= self.flush_count or
                        (time() - self.message_flush_last_t) >=
                        self.flush_interval):
                    print("Flushing...", len(self.message_buffer))
                    gc.collect()
                    memory_check()
                    await self.consumer.commit()
                    self.message_flush_last_t = time()
                    self.message_buffer.clear()


def memory_check():
    # https://tech.gadventures.com/hunting-for-memory-leaks-in-asyncio-applications-3614182efaf7
    if tracemalloc.is_tracing():
        snapshot = tracemalloc.take_snapshot()
        top_stats = snapshot.statistics('lineno')
        pprint([str(x) for x in top_stats[:10]])


def main():
    # Setup to properly handle KeyboardInterrupt exception
    loop = asyncio.get_event_loop()
    m_task = loop.create_task(Consumer().consume())
    m_task.add_done_callback(lambda task, loop=loop: loop.stop())

    try:
        loop.run_forever()
    except KeyboardInterrupt:
        m_task.cancel()
        loop.run_forever()
    finally:
        if not m_task.cancelled():
            m_task.result()

if __name__ == "__main__":
    main()
```

Are you sure you are using aiokafka==0.5.0 and not some older one. I tried Python3.6.4 and Python 3.7.2 with aiokafka 0.5.0 and master branch. No issues were found. Passed around 2000 messages per second.

**Comment by tvoinarovskyi** [comment]
Also I've released v0. 5.1 today, that may have some related fixes. Please try it if possible.

**Comment by diogovieira** [comment]
This new release indeed fixes the main issue!

Sorry for the delay but I was waiting for a few more tests.

I believe we may still have a (much) smaller memory problem that may be related to the fact that we're still using Python 3.6. But this one doesn't seem to grow linearly nor does it seems to impact that much the memory usage.

I can confirm we were using aiokafka 0.5.0 with Python 3.6.8.
